### ISSUE TITLE
The README file is not meaningful (enough) ;-)

### ISSUE THREAD

**Issue by jboockmann** [JungesAngebot/fake_news_tinder_webservice#1]

**Comment by frogg** [comment]
Jan du willst doch nicht etwa ein eigenes privates Tinder aufbauen? 😱😬😏

**Comment by noel-byT** [comment]
Ich bin also nicht der einzige, der eine Notification bekommen hat, haha. :D

**Comment by frogg** [comment]
Aber um da mal noch konstruktiv was beizutragen habe ich mal @Lavaquark angehauen. Der kann dazu bestimmt was sagen.
